EXERCISE_CATALOG = (
    {
        "id": "barbell-back-squat",
        "name": "Sentadilla trasera con barra",
        "slug": "barbell-back-squat",
        "primary_muscle_group": "Cuádriceps",
        "secondary_muscle_groups": [
            "Glúteos",
            "Isquiotibiales",
            "Core",
        ],
        "equipment": "barbell",
        "movement_pattern": "squat",
        "exercise_type": "compound",
        "variants": [
            "Sentadilla high bar",
            "Sentadilla low bar",
        ],
        "instructions": [
            "Apoya la barra de forma estable sobre la parte alta de la espalda.",
            "Mantén el tronco firme y las rodillas alineadas con los pies.",
            "Desciende con control y empuja el suelo para volver a subir.",
        ],
        "default_rep_range": "5-10",
    },
    {
        "id": "barbell-front-squat",
        "name": "Sentadilla frontal con barra",
        "slug": "barbell-front-squat",
        "primary_muscle_group": "Cuádriceps",
        "secondary_muscle_groups": [
            "Glúteos",
            "Core",
        ],
        "equipment": "barbell",
        "movement_pattern": "squat",
        "exercise_type": "compound",
        "variants": [
            "Agarre cruzado",
            "Agarre olímpico",
        ],
        "instructions": [
            "Coloca la barra sobre los deltoides anteriores.",
            "Mantén los codos altos durante todo el recorrido.",
            "Baja con control y mantén el torso lo más vertical posible.",
        ],
        "default_rep_range": "5-10",
    },
    {
        "id": "leg-press",
        "name": "Prensa de piernas",
        "slug": "leg-press",
        "primary_muscle_group": "Cuádriceps",
        "secondary_muscle_groups": [
            "Glúteos",
            "Isquiotibiales",
        ],
        "equipment": "machine",
        "movement_pattern": "squat",
        "exercise_type": "compound",
        "variants": [
            "Prensa inclinada",
            "Prensa horizontal",
            "Prensa vertical",
        ],
        "instructions": [
            "Apoya espalda y pelvis contra el respaldo.",
            "Controla la bajada sin perder el contacto lumbar.",
            "Empuja sin bloquear las rodillas de forma brusca.",
        ],
        "default_rep_range": "8-15",
    },
    {
        "id": "bulgarian-split-squat",
        "name": "Sentadilla búlgara",
        "slug": "bulgarian-split-squat",
        "primary_muscle_group": "Cuádriceps",
        "secondary_muscle_groups": [
            "Glúteos",
            "Isquiotibiales",
        ],
        "equipment": "dumbbell",
        "movement_pattern": "squat",
        "exercise_type": "compound",
        "variants": [
            "Con mancuernas",
            "Con barra",
            "Con peso corporal",
        ],
        "instructions": [
            "Eleva el pie trasero sobre un banco estable.",
            "Mantén la rodilla delantera alineada con el pie.",
            "Desciende de forma controlada y empuja con la pierna adelantada.",
        ],
        "default_rep_range": "8-15",
    },
    {
        "id": "barbell-romanian-deadlift",
        "name": "Peso muerto rumano con barra",
        "slug": "barbell-romanian-deadlift",
        "primary_muscle_group": "Isquiotibiales",
        "secondary_muscle_groups": [
            "Glúteos",
            "Erectores espinales",
            "Antebrazos",
        ],
        "equipment": "barbell",
        "movement_pattern": "hinge",
        "exercise_type": "compound",
        "variants": [
            "Con mancuernas",
            "A una pierna",
        ],
        "instructions": [
            "Mantén una ligera flexión de rodillas.",
            "Lleva la cadera atrás manteniendo la barra cerca del cuerpo.",
            "Detente al notar estiramiento de isquiotibiales sin perder neutralidad lumbar.",
        ],
        "default_rep_range": "6-12",
    },
    {
        "id": "barbell-deadlift",
        "name": "Peso muerto convencional",
        "slug": "barbell-deadlift",
        "primary_muscle_group": "Glúteos",
        "secondary_muscle_groups": [
            "Isquiotibiales",
            "Erectores espinales",
            "Dorsales",
            "Cuádriceps",
        ],
        "equipment": "barbell",
        "movement_pattern": "hinge",
        "exercise_type": "compound",
        "variants": [
            "Sumo",
            "Con déficit",
        ],
        "instructions": [
            "Coloca la barra sobre la parte media del pie.",
            "Genera tensión antes de despegar la barra del suelo.",
            "Empuja el suelo y mantén la barra cerca del cuerpo.",
        ],
        "default_rep_range": "3-8",
    },
    {
        "id": "barbell-hip-thrust",
        "name": "Hip thrust con barra",
        "slug": "barbell-hip-thrust",
        "primary_muscle_group": "Glúteos",
        "secondary_muscle_groups": [
            "Isquiotibiales",
            "Core",
        ],
        "equipment": "barbell",
        "movement_pattern": "hinge",
        "exercise_type": "compound",
        "variants": [
            "Con mancuerna",
            "En máquina",
            "A una pierna",
        ],
        "instructions": [
            "Apoya la parte alta de la espalda en un banco firme.",
            "Mantén las costillas controladas y la mirada al frente.",
            "Extiende la cadera y aprieta los glúteos sin hiperextender la espalda.",
        ],
        "default_rep_range": "8-15",
    },
    {
        "id": "barbell-bench-press",
        "name": "Press banca con barra",
        "slug": "barbell-bench-press",
        "primary_muscle_group": "Pectoral",
        "secondary_muscle_groups": [
            "Tríceps",
            "Deltoides anterior",
        ],
        "equipment": "barbell",
        "movement_pattern": "horizontal_push",
        "exercise_type": "compound",
        "variants": [
            "Agarre medio",
            "Agarre cerrado",
            "Con pausa",
        ],
        "instructions": [
            "Apoya firmemente pies, glúteos y parte alta de la espalda.",
            "Mantén los omóplatos retraídos y deprimidos.",
            "Baja la barra con control y empuja manteniendo las muñecas alineadas.",
        ],
        "default_rep_range": "5-12",
    },
    {
        "id": "dumbbell-incline-bench-press",
        "name": "Press inclinado con mancuernas",
        "slug": "dumbbell-incline-bench-press",
        "primary_muscle_group": "Pectoral",
        "secondary_muscle_groups": [
            "Tríceps",
            "Deltoides anterior",
        ],
        "equipment": "dumbbell",
        "movement_pattern": "horizontal_push",
        "exercise_type": "compound",
        "variants": [
            "Banco a 15 grados",
            "Banco a 30 grados",
            "Agarre neutro",
        ],
        "instructions": [
            "Ajusta una inclinación moderada del banco.",
            "Mantén hombros atrás y pecho elevado.",
            "Baja con control hasta un rango cómodo y empuja sin chocar mancuernas.",
        ],
        "default_rep_range": "8-15",
    },
    {
        "id": "parallel-bar-dip",
        "name": "Fondos en paralelas",
        "slug": "parallel-bar-dip",
        "primary_muscle_group": "Pectoral",
        "secondary_muscle_groups": [
            "Tríceps",
            "Deltoides anterior",
        ],
        "equipment": "bodyweight",
        "movement_pattern": "horizontal_push",
        "exercise_type": "compound",
        "variants": [
            "Con peso corporal",
            "Lastrados",
            "Asistidos",
        ],
        "instructions": [
            "Mantén los hombros alejados de las orejas.",
            "Inclina ligeramente el torso si buscas mayor implicación pectoral.",
            "Desciende solo hasta mantener el hombro cómodo y estable.",
        ],
        "default_rep_range": "6-15",
    },
    {
        "id": "barbell-overhead-press",
        "name": "Press militar con barra",
        "slug": "barbell-overhead-press",
        "primary_muscle_group": "Deltoides anterior",
        "secondary_muscle_groups": [
            "Tríceps",
            "Deltoides lateral",
            "Core",
        ],
        "equipment": "barbell",
        "movement_pattern": "vertical_push",
        "exercise_type": "compound",
        "variants": [
            "De pie",
            "Sentado",
            "Push press",
        ],
        "instructions": [
            "Aprieta glúteos y abdomen para estabilizar el tronco.",
            "Empuja la barra en línea vertical sobre el centro del cuerpo.",
            "Evita arquear en exceso la zona lumbar.",
        ],
        "default_rep_range": "5-12",
    },
    {
        "id": "dumbbell-lateral-raise",
        "name": "Elevación lateral con mancuernas",
        "slug": "dumbbell-lateral-raise",
        "primary_muscle_group": "Deltoides lateral",
        "secondary_muscle_groups": [
            "Trapecio superior",
        ],
        "equipment": "dumbbell",
        "movement_pattern": "isolation",
        "exercise_type": "isolation",
        "variants": [
            "De pie",
            "Sentado",
            "Inclinado",
        ],
        "instructions": [
            "Mantén una ligera flexión de codos.",
            "Eleva los brazos en el plano escapular de forma controlada.",
            "Evita balancear el torso o encoger excesivamente los hombros.",
        ],
        "default_rep_range": "10-20",
    },
    {
        "id": "pull-up",
        "name": "Dominadas",
        "slug": "pull-up",
        "primary_muscle_group": "Dorsales",
        "secondary_muscle_groups": [
            "Bíceps",
            "Romboides",
            "Trapecio medio",
        ],
        "equipment": "bodyweight",
        "movement_pattern": "vertical_pull",
        "exercise_type": "compound",
        "variants": [
            "Pronas",
            "Supinas",
            "Neutras",
            "Lastradas",
            "Asistidas",
        ],
        "instructions": [
            "Comienza con hombros activos y escápulas controladas.",
            "Lleva los codos hacia abajo y hacia atrás.",
            "Evita impulsarte con las piernas o acortar el recorrido.",
        ],
        "default_rep_range": "5-12",
    },
    {
        "id": "lat-pulldown",
        "name": "Jalón al pecho",
        "slug": "lat-pulldown",
        "primary_muscle_group": "Dorsales",
        "secondary_muscle_groups": [
            "Bíceps",
            "Romboides",
            "Trapecio medio",
        ],
        "equipment": "cable",
        "movement_pattern": "vertical_pull",
        "exercise_type": "compound",
        "variants": [
            "Agarre ancho",
            "Agarre neutro",
            "Agarre supino",
        ],
        "instructions": [
            "Fija las piernas bajo los apoyos.",
            "Inicia el gesto bajando las escápulas.",
            "Lleva la barra hacia la parte alta del pecho sin balancear el torso.",
        ],
        "default_rep_range": "8-15",
    },
    {
        "id": "barbell-row",
        "name": "Remo con barra",
        "slug": "barbell-row",
        "primary_muscle_group": "Espalda alta/media",
        "secondary_muscle_groups": [
            "Dorsales",
            "Bíceps",
            "Erectores espinales",
        ],
        "equipment": "barbell",
        "movement_pattern": "horizontal_pull",
        "exercise_type": "compound",
        "variants": [
            "Pendlay row",
            "Agarre supino",
        ],
        "instructions": [
            "Inclina el torso manteniendo la espalda neutra.",
            "Lleva la barra hacia el abdomen controlando los codos.",
            "Evita usar impulso de la zona lumbar.",
        ],
        "default_rep_range": "6-12",
    },
    {
        "id": "seated-cable-row",
        "name": "Remo sentado en polea",
        "slug": "seated-cable-row",
        "primary_muscle_group": "Espalda alta/media",
        "secondary_muscle_groups": [
            "Dorsales",
            "Bíceps",
            "Romboides",
        ],
        "equipment": "cable",
        "movement_pattern": "horizontal_pull",
        "exercise_type": "compound",
        "variants": [
            "Agarre neutro",
            "Agarre ancho",
            "A una mano",
        ],
        "instructions": [
            "Mantén el pecho alto y el torso estable.",
            "Lleva el agarre hacia el abdomen sin redondear la espalda.",
            "Controla el estiramiento al volver.",
        ],
        "default_rep_range": "8-15",
    },
    {
        "id": "barbell-biceps-curl",
        "name": "Curl con barra",
        "slug": "barbell-biceps-curl",
        "primary_muscle_group": "Bíceps",
        "secondary_muscle_groups": [
            "Braquial",
            "Antebrazos",
        ],
        "equipment": "barbell",
        "movement_pattern": "isolation",
        "exercise_type": "isolation",
        "variants": [
            "Barra recta",
            "Barra EZ",
            "Agarre estrecho",
        ],
        "instructions": [
            "Mantén los codos cerca del torso.",
            "Evita balancear la espalda para levantar la carga.",
            "Controla la bajada hasta extender cómodamente el codo.",
        ],
        "default_rep_range": "8-15",
    },
    {
        "id": "cable-triceps-pushdown",
        "name": "Extensión de tríceps en polea",
        "slug": "cable-triceps-pushdown",
        "primary_muscle_group": "Tríceps",
        "secondary_muscle_groups": [
            "Antebrazos",
        ],
        "equipment": "cable",
        "movement_pattern": "isolation",
        "exercise_type": "isolation",
        "variants": [
            "Barra recta",
            "Cuerda",
            "A una mano",
        ],
        "instructions": [
            "Fija los codos junto al cuerpo.",
            "Extiende los codos sin mover los hombros hacia delante.",
            "Controla el regreso sin perder tensión.",
        ],
        "default_rep_range": "10-20",
    },
    {
        "id": "lying-leg-curl",
        "name": "Curl femoral tumbado",
        "slug": "lying-leg-curl",
        "primary_muscle_group": "Isquiotibiales",
        "secondary_muscle_groups": [
            "Gemelos",
        ],
        "equipment": "machine",
        "movement_pattern": "isolation",
        "exercise_type": "isolation",
        "variants": [
            "Tumbado",
            "A una pierna",
        ],
        "instructions": [
            "Alinea la articulación de la máquina con la rodilla.",
            "Mantén la cadera apoyada durante todo el recorrido.",
            "Flexiona con control y evita despegar la pelvis.",
        ],
        "default_rep_range": "10-20",
    },
    {
        "id": "leg-extension",
        "name": "Extensión de cuádriceps",
        "slug": "leg-extension",
        "primary_muscle_group": "Cuádriceps",
        "secondary_muscle_groups": [],
        "equipment": "machine",
        "movement_pattern": "isolation",
        "exercise_type": "isolation",
        "variants": [
            "Bilateral",
            "Unilateral",
        ],
        "instructions": [
            "Alinea la rodilla con el eje de la máquina.",
            "Eleva la carga sin levantar la cadera del asiento.",
            "Controla la bajada y evita bloquear de forma brusca la rodilla.",
        ],
        "default_rep_range": "10-20",
    },
    {
        "id": "standing-calf-raise",
        "name": "Elevación de talones de pie",
        "slug": "standing-calf-raise",
        "primary_muscle_group": "Gemelos",
        "secondary_muscle_groups": [],
        "equipment": "machine",
        "movement_pattern": "isolation",
        "exercise_type": "isolation",
        "variants": [
            "En máquina",
            "Con mancuernas",
            "A una pierna",
        ],
        "instructions": [
            "Apoya el antepié de forma estable en la plataforma.",
            "Desciende los talones con control hasta sentir estiramiento.",
            "Eleva al máximo manteniendo una pausa breve arriba.",
        ],
        "default_rep_range": "10-20",
    },
    {
        "id": "cable-crunch",
        "name": "Crunch en polea",
        "slug": "cable-crunch",
        "primary_muscle_group": "Abdomen",
        "secondary_muscle_groups": [
            "Oblicuos",
        ],
        "equipment": "cable",
        "movement_pattern": "core",
        "exercise_type": "isolation",
        "variants": [
            "De rodillas",
            "De pie",
        ],
        "instructions": [
            "Fija la cuerda cerca de la frente o parte alta del pecho.",
            "Flexiona el tronco contrayendo el abdomen.",
            "Evita convertir el movimiento en una bisagra de cadera.",
        ],
        "default_rep_range": "10-20",
    },
    {
        "id": "plank",
        "name": "Plancha",
        "slug": "plank",
        "primary_muscle_group": "Abdomen",
        "secondary_muscle_groups": [
            "Glúteos",
            "Deltoides anterior",
        ],
        "equipment": "bodyweight",
        "movement_pattern": "core",
        "exercise_type": "isolation",
        "variants": [
            "Frontal",
            "Lateral",
            "Con carga",
        ],
        "instructions": [
            "Mantén hombros, cadera y tobillos alineados.",
            "Aprieta abdomen y glúteos durante toda la posición.",
            "Evita dejar caer o elevar demasiado la cadera.",
        ],
        "default_rep_range": "20-60 segundos",
    },
)