"""Esquema de PostgreSQL (migración 1).

Convenciones:
- Las fechas y marcas de tiempo son TEXT en formato ISO ("AAAA-MM-DD" y
  "AAAA-MM-DD HH:MM:SS" en UTC), igual que antes con SQLite, para que el
  resto del código no cambie.
- Los emails se guardan en minúsculas y son únicos sin distinguir mayúsculas
  gracias al índice sobre lower(email).
- Las tablas están en el esquema `public` de Supabase, que su API REST expone:
  por eso se activa RLS en todas (sin políticas, la API pública no puede leer
  nada). La aplicación se conecta con el rol propietario, que no se ve afectado.
"""

SCHEMA_STATEMENTS = [
    """
CREATE TABLE IF NOT EXISTS users (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        email TEXT NOT NULL
            CHECK (length(trim(email)) BETWEEN 3 AND 254),
        display_name TEXT NOT NULL
            CHECK (length(trim(display_name)) BETWEEN 1 AND 80),
        password_hash TEXT NOT NULL,
        is_active INTEGER NOT NULL DEFAULT 1
            CHECK (is_active IN (0, 1)),
        created_at TEXT NOT NULL DEFAULT (to_char(now() AT TIME ZONE 'utc', 'YYYY-MM-DD HH24:MI:SS')),
        token_version INTEGER NOT NULL DEFAULT 0
    )
    """,
    """
CREATE TABLE IF NOT EXISTS invitations (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        code_hash TEXT NOT NULL UNIQUE,
        created_at TEXT NOT NULL,
        expires_at TEXT NOT NULL,
        used_at TEXT,
        used_by_user_id INTEGER,
        FOREIGN KEY (used_by_user_id)
            REFERENCES users (id)
            ON DELETE SET NULL
    )
    """,
    """
CREATE TABLE IF NOT EXISTS password_resets (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        user_id INTEGER NOT NULL,
        code_hash TEXT NOT NULL UNIQUE,
        created_at TEXT NOT NULL,
        expires_at TEXT NOT NULL,
        used_at TEXT,
        FOREIGN KEY (user_id)
            REFERENCES users (id)
            ON DELETE CASCADE
    )
    """,
    """
CREATE TABLE IF NOT EXISTS daily_logs (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        user_id INTEGER NOT NULL,
        date TEXT NOT NULL,
        steps INTEGER NOT NULL DEFAULT 0 CHECK (steps >= 0),
        notes TEXT,
        created_at TEXT NOT NULL DEFAULT (to_char(now() AT TIME ZONE 'utc', 'YYYY-MM-DD HH24:MI:SS')),
        FOREIGN KEY (user_id)
            REFERENCES users(id)
            ON DELETE CASCADE,
        UNIQUE (user_id, date)
    )
    """,
    """
CREATE TABLE IF NOT EXISTS daily_recovery_logs (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        user_id INTEGER NOT NULL,
        date TEXT NOT NULL,
        sleep_minutes INTEGER
            CHECK (sleep_minutes >= 0 AND sleep_minutes <= 1440),
        sleep_quality INTEGER
            CHECK (sleep_quality >= 1 AND sleep_quality <= 5),
        is_rest_day INTEGER NOT NULL DEFAULT 0
            CHECK (is_rest_day IN (0, 1)),
        notes TEXT,
        created_at TEXT NOT NULL DEFAULT (to_char(now() AT TIME ZONE 'utc', 'YYYY-MM-DD HH24:MI:SS')),
        FOREIGN KEY (user_id)
            REFERENCES users(id)
            ON DELETE CASCADE,
        UNIQUE (user_id, date)
    )
    """,
    """
CREATE TABLE IF NOT EXISTS body_metrics (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        user_id INTEGER NOT NULL,
        date TEXT NOT NULL,
        weight_kg DOUBLE PRECISION NOT NULL CHECK (weight_kg > 0),
        height_cm DOUBLE PRECISION NOT NULL CHECK (height_cm > 0),
        bmi DOUBLE PRECISION NOT NULL CHECK (bmi > 0),
        body_fat_percentage DOUBLE PRECISION
            CHECK (
                body_fat_percentage > 0
                AND body_fat_percentage < 100
            ),
        waist_cm DOUBLE PRECISION CHECK (waist_cm > 0 AND waist_cm <= 300),
        hip_cm DOUBLE PRECISION CHECK (hip_cm > 0 AND hip_cm <= 300),
        chest_cm DOUBLE PRECISION CHECK (chest_cm > 0 AND chest_cm <= 300),
        arm_cm DOUBLE PRECISION CHECK (arm_cm > 0 AND arm_cm <= 200),
        thigh_cm DOUBLE PRECISION CHECK (thigh_cm > 0 AND thigh_cm <= 300),
        notes TEXT,
        created_at TEXT NOT NULL DEFAULT (to_char(now() AT TIME ZONE 'utc', 'YYYY-MM-DD HH24:MI:SS')),
        FOREIGN KEY (user_id)
            REFERENCES users(id)
            ON DELETE CASCADE,
        UNIQUE (user_id, date)
    )
    """,
    """
CREATE TABLE IF NOT EXISTS body_composition_goals (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        user_id INTEGER NOT NULL,
        metric_type TEXT NOT NULL CHECK (
            metric_type IN (
                'weight_kg', 'body_fat_percentage', 'waist_cm', 'hip_cm', 'chest_cm', 'arm_cm', 'thigh_cm'
            )
        ),
        target_value DOUBLE PRECISION NOT NULL CHECK (target_value > 0),
        direction TEXT NOT NULL CHECK (
            direction IN (
                'decrease', 'increase', 'maintain'
            )
        ),
        start_value DOUBLE PRECISION,
        started_at TEXT NOT NULL,
        created_at TEXT NOT NULL DEFAULT (to_char(now() AT TIME ZONE 'utc', 'YYYY-MM-DD HH24:MI:SS')),
        updated_at TEXT NOT NULL DEFAULT (to_char(now() AT TIME ZONE 'utc', 'YYYY-MM-DD HH24:MI:SS')),
        FOREIGN KEY (user_id)
            REFERENCES users(id)
            ON DELETE CASCADE,
        UNIQUE (user_id, metric_type)
    )
    """,
    """
CREATE TABLE IF NOT EXISTS fitness_goals (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        user_id INTEGER NOT NULL,
        goal_type TEXT NOT NULL CHECK (
            goal_type IN ('daily_steps', 'weekly_workouts', 'weekly_running_km', 'daily_calories', 'daily_protein_g', 'daily_carbs_g', 'daily_fat_g', 'daily_sleep_minutes', 'weekly_rest_days')
        ),
        target_value DOUBLE PRECISION NOT NULL CHECK (target_value > 0),
        created_at TEXT NOT NULL DEFAULT (to_char(now() AT TIME ZONE 'utc', 'YYYY-MM-DD HH24:MI:SS')),
        updated_at TEXT NOT NULL DEFAULT (to_char(now() AT TIME ZONE 'utc', 'YYYY-MM-DD HH24:MI:SS')),
        FOREIGN KEY (user_id)
            REFERENCES users(id)
            ON DELETE CASCADE,
        UNIQUE (user_id, goal_type)
    )
    """,
    """
CREATE TABLE IF NOT EXISTS runs (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        user_id INTEGER NOT NULL,
        date TEXT NOT NULL,
        distance_km DOUBLE PRECISION NOT NULL CHECK (distance_km > 0),
        duration_seconds INTEGER NOT NULL CHECK (duration_seconds > 0),
        average_pace_seconds_km DOUBLE PRECISION NOT NULL
            CHECK (average_pace_seconds_km > 0),
        notes TEXT,
        created_at TEXT NOT NULL DEFAULT (to_char(now() AT TIME ZONE 'utc', 'YYYY-MM-DD HH24:MI:SS')),
        FOREIGN KEY (user_id)
            REFERENCES users(id)
            ON DELETE CASCADE
    )
    """,
    """
CREATE TABLE IF NOT EXISTS workout_sessions (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        user_id INTEGER NOT NULL,
        date TEXT NOT NULL,
        name TEXT NOT NULL CHECK (length(trim(name)) > 0),
        notes TEXT,
        created_at TEXT NOT NULL DEFAULT (to_char(now() AT TIME ZONE 'utc', 'YYYY-MM-DD HH24:MI:SS')),
        FOREIGN KEY (user_id)
            REFERENCES users(id)
            ON DELETE CASCADE
    )
    """,
    """
CREATE TABLE IF NOT EXISTS workout_exercises (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        workout_session_id INTEGER NOT NULL,
        name TEXT NOT NULL CHECK (length(trim(name)) > 0),
        muscle_group TEXT NOT NULL CHECK (length(trim(muscle_group)) > 0),
        position INTEGER NOT NULL CHECK (position > 0),
        technique_notes TEXT,
        created_at TEXT NOT NULL DEFAULT (to_char(now() AT TIME ZONE 'utc', 'YYYY-MM-DD HH24:MI:SS')),
        FOREIGN KEY (workout_session_id)
            REFERENCES workout_sessions(id)
            ON DELETE CASCADE,
        UNIQUE (workout_session_id, position)
    )
    """,
    """
CREATE TABLE IF NOT EXISTS workout_sets (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        workout_exercise_id INTEGER NOT NULL,
        set_type TEXT NOT NULL CHECK (
            set_type IN ('warmup', 'approximation', 'working', 'drop_set')
        ),
        position INTEGER NOT NULL CHECK (position > 0),
        target_rep_range TEXT,
        repetitions INTEGER NOT NULL CHECK (repetitions > 0),
        weight_kg DOUBLE PRECISION NOT NULL CHECK (weight_kg >= 0),
        rir DOUBLE PRECISION CHECK (rir >= -3 AND rir <= 10),
        notes TEXT,
        created_at TEXT NOT NULL DEFAULT (to_char(now() AT TIME ZONE 'utc', 'YYYY-MM-DD HH24:MI:SS')),
        FOREIGN KEY (workout_exercise_id)
            REFERENCES workout_exercises(id)
            ON DELETE CASCADE,
        UNIQUE (workout_exercise_id, position)
    )
    """,
    """
CREATE TABLE IF NOT EXISTS workout_templates (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        user_id INTEGER NOT NULL,
        name TEXT NOT NULL CHECK (length(trim(name)) > 0),
        notes TEXT,
        created_at TEXT NOT NULL DEFAULT (to_char(now() AT TIME ZONE 'utc', 'YYYY-MM-DD HH24:MI:SS')),
        FOREIGN KEY (user_id)
            REFERENCES users(id)
            ON DELETE CASCADE
    )
    """,
    """
CREATE TABLE IF NOT EXISTS workout_template_exercises (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        workout_template_id INTEGER NOT NULL,
        name TEXT NOT NULL CHECK (length(trim(name)) > 0),
        muscle_group TEXT NOT NULL CHECK (length(trim(muscle_group)) > 0),
        position INTEGER NOT NULL CHECK (position > 0),
        technique_notes TEXT,
        created_at TEXT NOT NULL DEFAULT (to_char(now() AT TIME ZONE 'utc', 'YYYY-MM-DD HH24:MI:SS')),
        FOREIGN KEY (workout_template_id)
            REFERENCES workout_templates(id)
            ON DELETE CASCADE,
        UNIQUE (workout_template_id, position)
    )
    """,
    """
CREATE TABLE IF NOT EXISTS workout_template_sets (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        workout_template_exercise_id INTEGER NOT NULL,
        set_type TEXT NOT NULL CHECK (
            set_type IN ('warmup', 'approximation', 'working', 'drop_set')
        ),
        position INTEGER NOT NULL CHECK (position > 0),
        target_rep_range TEXT,
        repetitions INTEGER NOT NULL CHECK (repetitions > 0),
        weight_kg DOUBLE PRECISION NOT NULL CHECK (weight_kg >= 0),
        rir DOUBLE PRECISION CHECK (rir >= -3 AND rir <= 10),
        notes TEXT,
        created_at TEXT NOT NULL DEFAULT (to_char(now() AT TIME ZONE 'utc', 'YYYY-MM-DD HH24:MI:SS')),
        FOREIGN KEY (workout_template_exercise_id)
            REFERENCES workout_template_exercises(id)
            ON DELETE CASCADE,
        UNIQUE (workout_template_exercise_id, position)
    )
    """,
    """
CREATE TABLE IF NOT EXISTS planned_workouts (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        user_id INTEGER NOT NULL,
        scheduled_date TEXT NOT NULL,
        workout_template_id INTEGER,
        name TEXT NOT NULL CHECK (length(trim(name)) > 0),
        notes TEXT,
        status TEXT NOT NULL DEFAULT 'planned'
            CHECK (
                status IN (
                    'planned',
                    'completed',
                    'skipped'
                )
            ),
        workout_session_id INTEGER UNIQUE,
        created_at TEXT NOT NULL DEFAULT (to_char(now() AT TIME ZONE 'utc', 'YYYY-MM-DD HH24:MI:SS')),
        updated_at TEXT NOT NULL DEFAULT (to_char(now() AT TIME ZONE 'utc', 'YYYY-MM-DD HH24:MI:SS')),
        FOREIGN KEY (user_id)
            REFERENCES users(id)
            ON DELETE CASCADE,
        FOREIGN KEY (workout_template_id)
            REFERENCES workout_templates(id)
            ON DELETE SET NULL,
        FOREIGN KEY (workout_session_id)
            REFERENCES workout_sessions(id)
            ON DELETE SET NULL
    )
    """,
    """
CREATE TABLE IF NOT EXISTS nutrition_days (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        user_id INTEGER NOT NULL,
        date TEXT NOT NULL,
        notes TEXT,
        created_at TEXT NOT NULL DEFAULT (to_char(now() AT TIME ZONE 'utc', 'YYYY-MM-DD HH24:MI:SS')),
        FOREIGN KEY (user_id)
            REFERENCES users(id)
            ON DELETE CASCADE,
        UNIQUE (user_id, date)
    )
    """,
    """
CREATE TABLE IF NOT EXISTS nutrition_meals (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        nutrition_day_id INTEGER NOT NULL,
        name TEXT NOT NULL CHECK (length(trim(name)) > 0),
        position INTEGER NOT NULL CHECK (position > 0),
        created_at TEXT NOT NULL DEFAULT (to_char(now() AT TIME ZONE 'utc', 'YYYY-MM-DD HH24:MI:SS')),
        FOREIGN KEY (nutrition_day_id)
            REFERENCES nutrition_days(id)
            ON DELETE CASCADE,
        UNIQUE (nutrition_day_id, position)
    )
    """,
    """
CREATE TABLE IF NOT EXISTS nutrition_foods (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        nutrition_meal_id INTEGER NOT NULL,
        name TEXT NOT NULL CHECK (length(trim(name)) > 0),
        quantity_g DOUBLE PRECISION NOT NULL CHECK (quantity_g > 0),
        calories DOUBLE PRECISION NOT NULL CHECK (calories >= 0),
        protein_g DOUBLE PRECISION NOT NULL CHECK (protein_g >= 0),
        carbs_g DOUBLE PRECISION NOT NULL CHECK (carbs_g >= 0),
        fat_g DOUBLE PRECISION NOT NULL CHECK (fat_g >= 0),
        position INTEGER NOT NULL CHECK (position > 0),
        notes TEXT,
        created_at TEXT NOT NULL DEFAULT (to_char(now() AT TIME ZONE 'utc', 'YYYY-MM-DD HH24:MI:SS')),
        FOREIGN KEY (nutrition_meal_id)
            REFERENCES nutrition_meals(id)
            ON DELETE CASCADE,
        UNIQUE (nutrition_meal_id, position)
    )
    """,
    """
CREATE TABLE IF NOT EXISTS food_library (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        user_id INTEGER NOT NULL,
        name TEXT NOT NULL CHECK (length(trim(name)) > 0),
        calories_per_100g DOUBLE PRECISION NOT NULL
            CHECK (calories_per_100g >= 0),
        protein_per_100g DOUBLE PRECISION NOT NULL
            CHECK (protein_per_100g >= 0),
        carbs_per_100g DOUBLE PRECISION NOT NULL
            CHECK (carbs_per_100g >= 0),
        fat_per_100g DOUBLE PRECISION NOT NULL
            CHECK (fat_per_100g >= 0),
        notes TEXT,
        created_at TEXT NOT NULL DEFAULT (to_char(now() AT TIME ZONE 'utc', 'YYYY-MM-DD HH24:MI:SS')),
        updated_at TEXT NOT NULL DEFAULT (to_char(now() AT TIME ZONE 'utc', 'YYYY-MM-DD HH24:MI:SS')),
        FOREIGN KEY (user_id)
            REFERENCES users(id)
            ON DELETE CASCADE
    )
    """,
    """
CREATE TABLE IF NOT EXISTS meal_templates (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        user_id INTEGER NOT NULL,
        name TEXT NOT NULL CHECK (length(trim(name)) > 0),
        notes TEXT,
        created_at TEXT NOT NULL DEFAULT (to_char(now() AT TIME ZONE 'utc', 'YYYY-MM-DD HH24:MI:SS')),
        updated_at TEXT NOT NULL DEFAULT (to_char(now() AT TIME ZONE 'utc', 'YYYY-MM-DD HH24:MI:SS')),
        FOREIGN KEY (user_id)
            REFERENCES users(id)
            ON DELETE CASCADE
    )
    """,
    """
CREATE TABLE IF NOT EXISTS meal_template_items (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        meal_template_id INTEGER NOT NULL,
        name TEXT NOT NULL CHECK (length(trim(name)) > 0),
        quantity_g DOUBLE PRECISION NOT NULL CHECK (quantity_g > 0),
        calories_per_100g DOUBLE PRECISION NOT NULL
            CHECK (calories_per_100g >= 0),
        protein_per_100g DOUBLE PRECISION NOT NULL
            CHECK (protein_per_100g >= 0),
        carbs_per_100g DOUBLE PRECISION NOT NULL
            CHECK (carbs_per_100g >= 0),
        fat_per_100g DOUBLE PRECISION NOT NULL
            CHECK (fat_per_100g >= 0),
        position INTEGER NOT NULL CHECK (position > 0),
        notes TEXT,
        created_at TEXT NOT NULL DEFAULT (to_char(now() AT TIME ZONE 'utc', 'YYYY-MM-DD HH24:MI:SS')),
        FOREIGN KEY (meal_template_id)
            REFERENCES meal_templates(id)
            ON DELETE CASCADE,
        UNIQUE (meal_template_id, position)
    )
    """,
    """
CREATE INDEX IF NOT EXISTS idx_body_metrics_user_date ON body_metrics(user_id, date)
    """,
    """
CREATE INDEX IF NOT EXISTS idx_food_library_user_name ON food_library(user_id, name)
    """,
    """
CREATE INDEX IF NOT EXISTS idx_meal_templates_user_name ON meal_templates(user_id, name)
    """,
    """
CREATE INDEX IF NOT EXISTS idx_password_resets_user_id ON password_resets(user_id)
    """,
    """
CREATE INDEX IF NOT EXISTS idx_planned_workouts_user_date ON planned_workouts(user_id, scheduled_date)
    """,
    """
CREATE INDEX IF NOT EXISTS idx_planned_workouts_user_status_date ON planned_workouts(user_id, status, scheduled_date)
    """,
    """
CREATE INDEX IF NOT EXISTS idx_runs_user_date ON runs(user_id, date)
    """,
    """
CREATE INDEX IF NOT EXISTS idx_workout_templates_user_id ON workout_templates(user_id)
    """,
    """
CREATE UNIQUE INDEX IF NOT EXISTS idx_users_email_lower ON users (lower(email))
    """,
]

# Tablas a las que se aplica RLS, en el mismo orden que el esquema.
TABLES = [
    "users",
    "invitations",
    "password_resets",
    "daily_logs",
    "daily_recovery_logs",
    "body_metrics",
    "body_composition_goals",
    "fitness_goals",
    "runs",
    "workout_sessions",
    "workout_exercises",
    "workout_sets",
    "workout_templates",
    "workout_template_exercises",
    "workout_template_sets",
    "planned_workouts",
    "nutrition_days",
    "nutrition_meals",
    "nutrition_foods",
    "food_library",
    "meal_templates",
    "meal_template_items",
]

ROW_LEVEL_SECURITY_STATEMENTS = [
    f"ALTER TABLE {table} ENABLE ROW LEVEL SECURITY" for table in TABLES
] + [
    # En Supabase existen los roles anon y authenticated (los de su API
    # pública); en un PostgreSQL normal no, por eso la comprobación.
    """
    DO $$
    BEGIN
        IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'anon') THEN
            REVOKE ALL ON ALL TABLES IN SCHEMA public FROM anon;
        END IF;
        IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'authenticated') THEN
            REVOKE ALL ON ALL TABLES IN SCHEMA public FROM authenticated;
        END IF;
    END
    $$
    """,
]


# Migración 2: las sesiones planificadas pueden ser carreras. Una carrera tiene
# distancia objetivo y, al completarse, enlaza con el registro de running;
# no usa plantilla ni sesión de gimnasio. Lo garantizan estas restricciones.
PLANNED_RUNS_STATEMENTS = [
    """
ALTER TABLE planned_workouts
    ADD COLUMN kind TEXT NOT NULL DEFAULT 'workout'
        CHECK (kind IN ('workout', 'run'))
    """,
    """
ALTER TABLE planned_workouts
    ADD COLUMN target_distance_km DOUBLE PRECISION
        CHECK (target_distance_km > 0 AND target_distance_km <= 1000)
    """,
    """
ALTER TABLE planned_workouts
    ADD COLUMN run_id INTEGER UNIQUE
        REFERENCES runs(id) ON DELETE SET NULL
    """,
    """
ALTER TABLE planned_workouts
    ADD CONSTRAINT planned_workouts_run_only_fields CHECK (
        kind = 'run'
        OR (target_distance_km IS NULL AND run_id IS NULL)
    )
    """,
    """
ALTER TABLE planned_workouts
    ADD CONSTRAINT planned_workouts_run_has_no_gym_fields CHECK (
        kind = 'workout'
        OR (workout_template_id IS NULL AND workout_session_id IS NULL)
    )
    """,
]
